### ISSUE TITLE
3scale-cli config: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by daffinm** [3scale/3scale-cli#37]
Just installed 3scale-cli on Ubuntu 16.04. Ran 3scale-cli config and got the following error. Bug?
```
$ 3scale-cli config
/usr/local/lib/node_modules/node-3scale-cli/node_modules/delay-promise/index.js:11
function creator(...args) {
                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-3scale-cli/lib/swagger.js:6:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by VinayBhalerao** [comment]
@daffinm Can you please paste the node and npm version? and are you running the master or release https://github.com/3scale/3scale-cli/releases/tag/v0.10.1 candidate?

**Comment by daffinm** [comment]
@VinayBhalerao I installed npm from the default repos on Ubuntu 16.04:

> $ npm -v
> 3.5.2
> $ node -v
> v4.2.6

And I installed the 3scale-cli using the instructions in the project md file: 

> npm install -g node-3scale-cli

> $ npm list -g | grep 3scale-cli
> └─┬ node-3scale-cli@0.10.2

**Comment by daffinm** [comment]
Hi @VinayBhalerao Any update on this one? I would really like to try adding methods in this way. We have a beta release this week and it would be very useful not to have to add all the methods manually.

**Comment by daffinm** [comment]
OK. Sorry folks. I was using an old version NPM. I have just installed v8 using [these notes](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) and 3scale-cli config is running as expected.
