### ISSUE TITLE
error with status code 422 when trying to import to saas

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale-cli#51]
When trying to execute the following:
`3scale-cli import swagger -f json_vcc.json`

I received the following error:```

[ 3scale-cli ] Loading Profiles API37 swagger definition. 
[ 3scale-cli ] Service with id 2555417747254 created on 3scale 
[ 3scale-cli ] Hits metric with id 2555418049462 found on 3scale 
[ 3scale-cli ] Method ndefined_about_assembly_version_GET with system_name ndefined_about_assembly_version_GET created on 3scale. 
[ 3scale-cli ] Method ndefined_self_GET with system_name ndefined_self_GET created on 3scale. 
[ 3scale-cli ] Method ndefined_self_PUT with system_name ndefined_self_PUT created on 3scale. 
[ 3scale-cli ] Method ndefined_settings_market_GET with system_name ndefined_settings_market_GET created on 3scale. 
[ 3scale-cli ] Method ndefined_settings_fields_GET with system_name ndefined_settings_fields_GET created on 3scale. 
[3scale-cli] ERROR encountered on creating Mapping rule: undefined
/usr/lib/node_modules/node-3scale-cli/node_modules/q/q.js:155
                throw e;
                ^

Error: Server responded with status code 422 undefined
    at /usr/lib/node_modules/node-3scale-cli/lib/mappingrules.js:29:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at createMappingRulePromise (/usr/lib/node_modules/node-3scale-cli/lib/swagger.js:131:116)
    at /usr/lib/node_modules/node-3scale-cli/node_modules/delay-promise/index.js:15:18
    at delay.then (/usr/lib/node_modules/node-3scale-cli/node_modules/delay-promise/index.js:8:33)
From previous event:
    at threescale_waterfall (/usr/lib/node_modules/node-3scale-cli/lib/swagger.js:92:4)
    at /usr/lib/node_modules/node-3scale-cli/lib/swagger.js:40:11
```

the swagger definition is attached.
[swagger.json.txt](https://github.com/3scale/3scale-cli/files/1207820/swagger.json.txt)

**Comment by picsoung** [comment]
@lucamaf this issue comes because the property `basePath` is not defined in the spec.
I would recommend to define it `basePath` even if it's just `/` and it will work.

**Comment by lucamaf** [comment]
is it possible to catch this specific error and provide the indication in the error stack?

**Comment by picsoung** [comment]
there are many reasons why this could throw a 422 error.

in the last version the `422 undefined` is replaced with `422 <details of the error`
